// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtZZGucolJxd0uE0fmX8Nm9PIOqdwN39U',
    appId: '1:769425184635:web:5e4739d8655e021c288fde',
    messagingSenderId: '769425184635',
    projectId: 'attendance-86c04',
    authDomain: 'attendance-86c04.firebaseapp.com',
    databaseURL: 'https://attendance-86c04-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-86c04.appspot.com',
    measurementId: 'G-X11J09RH0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8EXlj1-kGRPwxxlZbYr9PjLdb09JtGU',
    appId: '1:769425184635:android:934bcbfd8e82f015288fde',
    messagingSenderId: '769425184635',
    projectId: 'attendance-86c04',
    databaseURL: 'https://attendance-86c04-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-86c04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvoRwWNPnriLUUH0pCMJIxG1RvIXkkVSE',
    appId: '1:769425184635:ios:09b9ac2dd1f98b22288fde',
    messagingSenderId: '769425184635',
    projectId: 'attendance-86c04',
    databaseURL: 'https://attendance-86c04-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-86c04.appspot.com',
    iosBundleId: 'com.example.feAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvoRwWNPnriLUUH0pCMJIxG1RvIXkkVSE',
    appId: '1:769425184635:ios:09b9ac2dd1f98b22288fde',
    messagingSenderId: '769425184635',
    projectId: 'attendance-86c04',
    databaseURL: 'https://attendance-86c04-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-86c04.appspot.com',
    iosBundleId: 'com.example.feAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtZZGucolJxd0uE0fmX8Nm9PIOqdwN39U',
    appId: '1:769425184635:web:69c7443e2631a181288fde',
    messagingSenderId: '769425184635',
    projectId: 'attendance-86c04',
    authDomain: 'attendance-86c04.firebaseapp.com',
    databaseURL: 'https://attendance-86c04-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-86c04.appspot.com',
    measurementId: 'G-3MP8J2B981',
  );
}
